#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
bsp-assistant modlibs library-manager config_usbdev usbdev-configurator qspi-configurator config_ezpd ez-pd-configurator config device-configurator seglcd-configurator dfuh-tool smartio-configurator :
	make -C proj_cm33_ns $@

config_bt bt-configurator deepcraftmodelconverter :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: bsp-assistant modlibs library-manager config_usbdev usbdev-configurator qspi-configurator config_ezpd ez-pd-configurator config device-configurator seglcd-configurator config_bt bt-configurator dfuh-tool smartio-configurator deepcraftmodelconverter
