/***************************************************************************//**
* \file MODEL_E84_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains MODEL_E84 model data.
* Date: 2026-09-09T15:40:38.085448+05:30
*******************************************************************************
* (c) 2019-2026, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*******************************************************************************
* This software, including source code, documentation and related materials
* (&#34;Software&#34;), is owned by Cypress Semiconductor Corporation or one of its
* subsidiaries (&#34;Cypress&#34;) and is protected by and subject to worldwide patent
* protection (United States and foreign), United States copyright laws and
* international treaty provisions. Therefore, you may use this Software only
* as provided in the license agreement accompanying the software package from
* which you obtained this Software (&#34;EULA&#34;).
*
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software source
* code solely for use in connection with Cypress&#39;s integrated circuit products.
* Any reproduction, modification, translation, compilation, or representation
* of this Software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death (&#34;High Risk Product&#34;). By
* including Cypress&#39;s product in a High Risk Product, the manufacturer of such
* system or application assumes all risk of such use and in doing so agrees to
* indemnify Cypress against all liability.
*******************************************************************************/
/*
ml-coretools 3.3.0.9784 based on TensorFlow 2.19.0 and ethos-u-vela 5.0.0
    ml-coretools-middleware-streaming 3.4.0.16924
    ml-coretools-tflm-qemu-images 3.4.0.16924
*/

#ifndef MODEL_E84_TFLM_MODEL_INT8X8_H
#define MODEL_E84_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t MODEL_E84_model_bin[];
#else
extern uint8_t MODEL_E84_model_bin[];
#endif // CY_ML_MODEL_MEM
#define MODEL_E84_MODEL_BIN_LEN (4344016u)
#define MODEL_E84_ARENA_SIZE (1135616u)

#endif // MODEL_E84_TFLM_MODEL_INT8X8_H